language: python
python:
  - "3.4"

# use docker containers, faster
sudo: false

cache: pip
install:
  - pip install --upgrade pip wheel
  - pip install -r requirements.txt
  - pip install pyflakes pylint

script:
  - pyflakes .
  - pylint --errors-only --disable=all --enable=duplicate-key inspectors/*.py inspectors/utils/*.py scripts/*.py igs qa backup

notifications:
  email:
    recipients:
      - spulec@gmail.com
      - eric@konklone.com
    on_success: change
    on_failure: change
